[package]
name = "gpfind"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
description = "Gluster Parallel Find"
license = "MIT"

[dependencies]
clap = "*"
gfapi-sys = "*"
libc = "*"
log = "*"
multiqueue = "*"
r2d2 = "*"
r2d2_gluster = "*"
simplelog = "*"
